### ISSUE TITLE
consider a move to a js site generator

### ISSUE THREAD

**Issue by travi** [dsmjs/dsmjs.github.io#24]
since it seems like the current list of issues is close to a complete redo of the site, this might be a good chance to consider moving to something other than jekyll. since this is a js group, would it make sense to use one built on js?

[gatsby](https://github.com/gatsbyjs/gatsby) and [phenomic](https://phenomic.io/) are a few that i've been exploring lately because they are based on react and react-router, but there are [plenty of others](https://www.staticgen.com/), like [assemble](http://assemble.io/), out there too.

**Comment by PaulSearcy** [comment]
How does [Nuxt](https://nuxtjs.org/) with [Netlfiy CMS](https://github.com/netlify/netlify-cms) sound?

A Vue based static site generator with a React based add on simple React CMS? :grinning:

I'm up for a challenge and always like trying to combine tech from two different but similar communities.

**Comment by travi** [comment]
a CMS seems heavy for what we need, even if it does generate a static site. as you can tell from the progress of some of these issues, this stuff is a bit starved for attn, so we need to keep maintenance as simple as possible (i dont think this is the right project to fulfill being up for a challenge). plus we want contributions to be very simple, but i think its reasonable to expect anyone sending us a PR to be able to edit a markdown file w/o the help of a CMS admin interface.

Since I'm likely to be the one with the primary responsibility for maintenance for the foreseeable future, I'd prefer to stick to full react, without introducing something additional like Vue. I think I'm really leaning toward gatsby, listed above, and plan to use the components that I've started to break out [here](https://github.com/dsmjs/components/).

as far as deployment goes, it doesnt get much easier than deploying to github pages, so i'd like to stay [consistent](https://github.com/dsmjs/components/blob/23616ac281f79e0f1fe00cda713ed5659e3f4e0c/.travis.yml#L14-L17) unless we have a really good reason not to.

**Comment by crolek** [comment]
CMS:
I don't think dsmJS really has a need for one yet and that's because a majority of the posts are done by me. I get the info from the speaker/sponsor, make a new markdown file, and `jekyll serve` it, tweak, and push. If we got to the point where I had Sponsors/non-tech-speakers submitting info on a regular basis I'd be fine with that idea. 
In all honesty, I know a recent big refactor was done with good intentions, but it keeps causing me problems. I say I'm going to fix/document/something, I forget about it for a month, and then 30ish days later I'm back in the same spot. dsmJS operates on the minimalist of effort/infrastructure because we can. (and we let ourselves) 


CDN:
We have been evaluating putting Cloudflare in front of dsmJS so we can get the free SSL. Personally I don't think we need a true "CDN" because our traffic is so low, but the SSL would be nice.

**Comment by travi** [comment]
cloudflare ssl is [already in place](https://github.com/dsmjs/dsmjs.github.io/issues/15) ;)

**Comment by crolek** [comment]
Oh yeah. Well I'm going to sleep now. :D

**Comment by travi** [comment]
This is finally a WIP. Closing this issue since the work on the new Gatsby site is happening in [a separate repo](https://github.com/dsmjs/site)
